"""empty message

Revision ID: db3374920aff
Revises: 1cd00e0a3f8a
Create Date: 2020-11-03 20:56:15.443672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3374920aff'
down_revision = '1cd00e0a3f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('usr_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'user', ['usr_id'], ['id'])
    op.drop_column('event', 'user_id')
    op.add_column('user_favorites', sa.Column('usr_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'user_favorites', type_='foreignkey')
    op.create_foreign_key(None, 'user_favorites', 'user', ['usr_id'], ['id'])
    op.drop_column('user_favorites', 'user_id')
    op.add_column('user_image', sa.Column('usr_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'user_image', type_='foreignkey')
    op.create_foreign_key(None, 'user_image', 'user', ['usr_id'], ['id'])
    op.drop_column('user_image', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_image', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'user_image', type_='foreignkey')
    op.create_foreign_key(None, 'user_image', 'user', ['user_id'], ['id'])
    op.drop_column('user_image', 'usr_id')
    op.add_column('user_favorites', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'user_favorites', type_='foreignkey')
    op.create_foreign_key(None, 'user_favorites', 'user', ['user_id'], ['id'])
    op.drop_column('user_favorites', 'usr_id')
    op.add_column('event', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'user', ['user_id'], ['id'])
    op.drop_column('event', 'usr_id')
    # ### end Alembic commands ###
